### ISSUE TITLE
spanish model

### ISSUE THREAD

**Issue by elbaulp** [rohit-jain/parzer#2]
Hi, it would be possible if you upload the spanish model please? Or show me how could I train a spanish model using your code?

When I run 

``` python
python parser/__init__.py -c 5120 -i spanish -t stanford
```

I get:

``` python
IOError: [Errno 2] No such file or directory: '/home/hkr/ssd2/TFG/Desarrollo/dp/models/spanish_stanford/svm.p'
```

And indeed, there is not such file called `svm.p`.

Best regards and thanks.

**Comment by rohit-jain** [comment]
Hi,

You can download the models by going to the following URL http://bit.ly/nlp-cs6741-full. There are some models in the models folder.

**Comment by elbaulp** [comment]
Thanks, the svm.p file did not was there previously. 

Best regards!

**Comment by rohit-jain** [comment]
yep, it's not there in the github code because of upload limits. There are instructions in the README files which point to the URL for downloading the models. Hope that helps.
